apiVersion: 1

contactPoints:
  - orgId: 1
    name: administrateur
    receivers:
      - uid: administrateur-email
        type: email
        settings:
          addresses: $__env{GRAFANA_ALERT_EMAIL}
          singleEmail: true

policies:
  - orgId: 1
    receiver: administrateur
    group_by: ["alertname"]
    group_wait: 5s
    group_interval: 30s
    repeat_interval: 1h
